-- ============================================================================
-- Estate CRM — seed a comprehensive list of Dubai / UAE real-estate developers.
-- Safe to run more than once: each row is only inserted if its name isn't
-- already present (no unique constraint required). Does not touch existing rows.
-- Run this in the Supabase SQL editor.
-- ============================================================================

insert into public.developers (name, website)
select v.name, nullif(v.website, '')
from (values
  ('Emaar Properties', 'https://www.emaar.com'),
  ('DAMAC Properties', 'https://www.damacproperties.com'),
  ('Nakheel', 'https://www.nakheel.com'),
  ('Meraas', 'https://www.meraas.com'),
  ('Dubai Properties', 'https://www.dp.ae'),
  ('Sobha Realty', 'https://www.sobharealty.com'),
  ('Azizi Developments', 'https://www.azizidevelopments.com'),
  ('Danube Properties', 'https://www.danubeproperties.com'),
  ('Binghatti Developers', 'https://www.binghatti.com'),
  ('Ellington Properties', 'https://ellingtonproperties.ae'),
  ('Select Group', 'https://www.select-group.ae'),
  ('Omniyat', 'https://www.omniyat.com'),
  ('MAG Property Development', 'https://www.mag.ae'),
  ('Deyaar Development', 'https://www.deyaar.ae'),
  ('Union Properties', 'https://www.up.ae'),
  ('Nshama', 'https://www.nshama.com'),
  ('Aldar Properties', 'https://www.aldar.com'),
  ('Arada', 'https://www.arada.com'),
  ('Samana Developers', 'https://samanagroup.ae'),
  ('Tiger Properties', ''),
  ('Object 1', ''),
  ('Wasl Properties', 'https://www.wasl.ae'),
  ('Al Habtoor Group', 'https://www.alhabtoorgroup.com'),
  ('Majid Al Futtaim', 'https://www.majidalfuttaim.com'),
  ('Bloom Holding', 'https://www.bloomholding.com'),
  ('Reportage Properties', 'https://reportageuae.com'),
  ('Imtiaz Developments', 'https://imtiaz.ae'),
  ('LEOS Developments', 'https://leosdevelopments.com'),
  ('Vincitore Real Estate', 'https://www.vincitorerealestate.com'),
  ('Prestige One', 'https://prestigeonedevelopments.com'),
  ('AYS Developers', ''),
  ('Meteora', ''),
  ('Pantheon Development', ''),
  ('Iman Developers', ''),
  ('Sol Properties', ''),
  ('Q Properties', ''),
  ('Palma Holding', ''),
  ('Seven Tides', 'https://seventides.com'),
  ('Esnaad', ''),
  ('RAK Properties', 'https://www.rakproperties.net'),
  ('Eagle Hills', 'https://www.eaglehills.com'),
  ('Modon Properties', 'https://www.modon.ae'),
  ('Alef Group', 'https://www.alefgroup.ae'),
  ('Expo City Dubai', 'https://www.expocitydubai.com'),
  ('Dubai South', 'https://www.dubaisouth.ae'),
  ('Ohana Development', ''),
  ('Swiss Property', ''),
  ('Peace Homes Development', ''),
  ('Mira Developments', ''),
  ('Aqua Properties', ''),
  ('Devmark', ''),
  ('Nabni Developments', ''),
  ('HRE Development', ''),
  ('Empire Development', ''),
  ('Townx Real Estate', ''),
  ('Almazaya Holding', ''),
  ('Tuscany Real Estate Development', ''),
  ('Wellington Developments', ''),
  ('Forum Real Estate', ''),
  ('Zimaya Properties', ''),
  ('Saas Properties', ''),
  ('Acube Developments', ''),
  ('Segrex Development', ''),
  ('BNW Developments', ''),
  ('Gulf Land Property Developers', ''),
  ('Condor Group', ''),
  ('Dugasta Properties', ''),
  ('Riviera Group', ''),
  ('Lootah Real Estate Development', ''),
  ('Signature Developers', ''),
  ('Five Holdings', 'https://www.fivehotelsandresorts.com')
) as v(name, website)
where not exists (
  select 1 from public.developers d where lower(d.name) = lower(v.name)
);
